import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import OrderCacheProvider from "@/components/provider/order-cache-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Superole Order System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <OrderCacheProvider>
          {children}
          <Toaster />
        </OrderCacheProvider>
      </body>
    </html>
  );
}
